# Generated by Django 4.0.2 on 2022-03-30 22:19

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ልጣፍ',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ኣርእስቲ', models.CharField(max_length=100)),
                ('ትሕዝቶ', models.TextField()),
                ('ዕለት', models.DateTimeField(default=django.utils.timezone.now)),
                ('ደራሲ', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
